-- Final business enhancements. Backup first. Apply after phase5.sql. Safe to repeat.
USE campus_repair;
SET NAMES utf8mb4;
SET @campus_new_workflow = (SELECT COUNT(*)=0 FROM information_schema.table_constraints WHERE table_schema=DATABASE() AND table_name='repair_order' AND constraint_name='chk_workflow_migration_complete');
SET @campus_ddl = IF((SELECT COUNT(*) FROM information_schema.columns WHERE table_schema=DATABASE() AND table_name='repair_order' AND column_name='repair_round')=0, 'ALTER TABLE repair_order ADD COLUMN repair_round INT NOT NULL DEFAULT 1', 'SELECT 1');
PREPARE campus_stmt FROM @campus_ddl; EXECUTE campus_stmt; DEALLOCATE PREPARE campus_stmt;
SET @campus_ddl = IF((SELECT COUNT(*) FROM information_schema.columns WHERE table_schema=DATABASE() AND table_name='repair_order' AND column_name='dispatch_round')=0, 'ALTER TABLE repair_order ADD COLUMN dispatch_round INT NOT NULL DEFAULT 0', 'SELECT 1');
PREPARE campus_stmt FROM @campus_ddl; EXECUTE campus_stmt; DEALLOCATE PREPARE campus_stmt;
SET @campus_ddl = IF((SELECT COUNT(*) FROM information_schema.columns WHERE table_schema=DATABASE() AND table_name='repair_order' AND column_name='assigned_time')=0, 'ALTER TABLE repair_order ADD COLUMN assigned_time DATETIME NULL', 'SELECT 1');
PREPARE campus_stmt FROM @campus_ddl; EXECUTE campus_stmt; DEALLOCATE PREPARE campus_stmt;
SET @campus_ddl = IF((SELECT COUNT(*) FROM information_schema.columns WHERE table_schema=DATABASE() AND table_name='repair_order' AND column_name='accepted_time')=0, 'ALTER TABLE repair_order ADD COLUMN accepted_time DATETIME NULL', 'SELECT 1');
PREPARE campus_stmt FROM @campus_ddl; EXECUTE campus_stmt; DEALLOCATE PREPARE campus_stmt;
SET @campus_ddl = IF((SELECT COUNT(*) FROM information_schema.columns WHERE table_schema=DATABASE() AND table_name='repair_order' AND column_name='started_time')=0, 'ALTER TABLE repair_order ADD COLUMN started_time DATETIME NULL', 'SELECT 1');
PREPARE campus_stmt FROM @campus_ddl; EXECUTE campus_stmt; DEALLOCATE PREPARE campus_stmt;
SET @campus_ddl = IF((SELECT COUNT(*) FROM information_schema.columns WHERE table_schema=DATABASE() AND table_name='repair_order' AND column_name='response_due_time')=0, 'ALTER TABLE repair_order ADD COLUMN response_due_time DATETIME NULL', 'SELECT 1');
PREPARE campus_stmt FROM @campus_ddl; EXECUTE campus_stmt; DEALLOCATE PREPARE campus_stmt;
SET @campus_ddl = IF((SELECT COUNT(*) FROM information_schema.columns WHERE table_schema=DATABASE() AND table_name='repair_order' AND column_name='repair_due_time')=0, 'ALTER TABLE repair_order ADD COLUMN repair_due_time DATETIME NULL', 'SELECT 1');
PREPARE campus_stmt FROM @campus_ddl; EXECUTE campus_stmt; DEALLOCATE PREPARE campus_stmt;
SET @campus_ddl = IF((SELECT COUNT(*) FROM information_schema.columns WHERE table_schema=DATABASE() AND table_name='repair_order' AND column_name='overdue_type')=0, 'ALTER TABLE repair_order ADD COLUMN overdue_type VARCHAR(16) NULL', 'SELECT 1');
PREPARE campus_stmt FROM @campus_ddl; EXECUTE campus_stmt; DEALLOCATE PREPARE campus_stmt;
SET @campus_ddl = IF((SELECT COUNT(*) FROM information_schema.columns WHERE table_schema=DATABASE() AND table_name='repair_order' AND column_name='appointment_start')=0, 'ALTER TABLE repair_order ADD COLUMN appointment_start DATETIME NULL', 'SELECT 1');
PREPARE campus_stmt FROM @campus_ddl; EXECUTE campus_stmt; DEALLOCATE PREPARE campus_stmt;
SET @campus_ddl = IF((SELECT COUNT(*) FROM information_schema.columns WHERE table_schema=DATABASE() AND table_name='repair_order' AND column_name='appointment_end')=0, 'ALTER TABLE repair_order ADD COLUMN appointment_end DATETIME NULL', 'SELECT 1');
PREPARE campus_stmt FROM @campus_ddl; EXECUTE campus_stmt; DEALLOCATE PREPARE campus_stmt;
SET @campus_ddl = IF((SELECT COUNT(*) FROM information_schema.columns WHERE table_schema=DATABASE() AND table_name='repair_order' AND column_name='appointment_status')=0, 'ALTER TABLE repair_order ADD COLUMN appointment_status VARCHAR(16) NOT NULL DEFAULT \'NONE\'', 'SELECT 1');
PREPARE campus_stmt FROM @campus_ddl; EXECUTE campus_stmt; DEALLOCATE PREPARE campus_stmt;
SET @campus_ddl = IF((SELECT COUNT(*) FROM information_schema.columns WHERE table_schema=DATABASE() AND table_name='repair_order' AND column_name='appointment_reason')=0, 'ALTER TABLE repair_order ADD COLUMN appointment_reason VARCHAR(500) NULL', 'SELECT 1');
PREPARE campus_stmt FROM @campus_ddl; EXECUTE campus_stmt; DEALLOCATE PREPARE campus_stmt;
SET @campus_ddl = IF((SELECT COUNT(*) FROM information_schema.columns WHERE table_schema=DATABASE() AND table_name='repair_order' AND column_name='appointment_version')=0, 'ALTER TABLE repair_order ADD COLUMN appointment_version INT NOT NULL DEFAULT 0', 'SELECT 1');
PREPARE campus_stmt FROM @campus_ddl; EXECUTE campus_stmt; DEALLOCATE PREPARE campus_stmt;
SET @campus_ddl = IF((SELECT COUNT(*) FROM information_schema.columns WHERE table_schema=DATABASE() AND table_name='order_event' AND column_name='content')=0, 'ALTER TABLE order_event ADD COLUMN content VARCHAR(2000) NULL', 'SELECT 1');
PREPARE campus_stmt FROM @campus_ddl; EXECUTE campus_stmt; DEALLOCATE PREPARE campus_stmt;
SET @campus_ddl = IF((SELECT COUNT(*) FROM information_schema.columns WHERE table_schema=DATABASE() AND table_name='order_event' AND column_name='round_no')=0, 'ALTER TABLE order_event ADD COLUMN round_no INT NOT NULL DEFAULT 1', 'SELECT 1');
PREPARE campus_stmt FROM @campus_ddl; EXECUTE campus_stmt; DEALLOCATE PREPARE campus_stmt;
SET @campus_ddl = IF((SELECT COUNT(*) FROM information_schema.columns WHERE table_schema=DATABASE() AND table_name='order_event' AND column_name='worker_id')=0, 'ALTER TABLE order_event ADD COLUMN worker_id BIGINT UNSIGNED NULL', 'SELECT 1');
PREPARE campus_stmt FROM @campus_ddl; EXECUTE campus_stmt; DEALLOCATE PREPARE campus_stmt;
SET @campus_ddl = IF((SELECT COUNT(*) FROM information_schema.columns WHERE table_schema=DATABASE() AND table_name='dispatch_record' AND column_name='round_no')=0, 'ALTER TABLE dispatch_record ADD COLUMN round_no INT NOT NULL DEFAULT 0', 'SELECT 1');
PREPARE campus_stmt FROM @campus_ddl; EXECUTE campus_stmt; DEALLOCATE PREPARE campus_stmt;
SET @campus_ddl = IF((SELECT COUNT(*) FROM information_schema.columns WHERE table_schema=DATABASE() AND table_name='dispatch_record' AND column_name='decision')=0, 'ALTER TABLE dispatch_record ADD COLUMN decision VARCHAR(16) NOT NULL DEFAULT \'RECOMMENDED\'', 'SELECT 1');
PREPARE campus_stmt FROM @campus_ddl; EXECUTE campus_stmt; DEALLOCATE PREPARE campus_stmt;
SET @campus_ddl = IF((SELECT COUNT(*) FROM information_schema.columns WHERE table_schema=DATABASE() AND table_name='dispatch_record' AND column_name='method')=0, 'ALTER TABLE dispatch_record ADD COLUMN method VARCHAR(16) NOT NULL DEFAULT \'SMART\'', 'SELECT 1');
PREPARE campus_stmt FROM @campus_ddl; EXECUTE campus_stmt; DEALLOCATE PREPARE campus_stmt;
SET @campus_ddl = IF((SELECT COUNT(*) FROM information_schema.columns WHERE table_schema=DATABASE() AND table_name='dispatch_record' AND column_name='reject_reason')=0, 'ALTER TABLE dispatch_record ADD COLUMN reject_reason VARCHAR(500) NULL', 'SELECT 1');
PREPARE campus_stmt FROM @campus_ddl; EXECUTE campus_stmt; DEALLOCATE PREPARE campus_stmt;
SET @campus_ddl = IF((SELECT COUNT(*) FROM information_schema.columns WHERE table_schema=DATABASE() AND table_name='dispatch_record' AND column_name='response_time')=0, 'ALTER TABLE dispatch_record ADD COLUMN response_time DATETIME NULL', 'SELECT 1');
PREPARE campus_stmt FROM @campus_ddl; EXECUTE campus_stmt; DEALLOCATE PREPARE campus_stmt;
SET @campus_ddl = IF((SELECT COUNT(*) FROM information_schema.columns WHERE table_schema=DATABASE() AND table_name='repair_record' AND column_name='round_no')=0, 'ALTER TABLE repair_record ADD COLUMN round_no INT NOT NULL DEFAULT 1', 'SELECT 1');
PREPARE campus_stmt FROM @campus_ddl; EXECUTE campus_stmt; DEALLOCATE PREPARE campus_stmt;
ALTER TABLE order_event MODIFY actor_id BIGINT UNSIGNED NULL;
ALTER TABLE dispatch_record MODIFY skill_score DECIMAL(5,2) NULL, MODIFY distance_score DECIMAL(5,2) NULL, MODIFY load_score DECIMAL(5,2) NULL, MODIFY rating_score DECIMAL(5,2) NULL, MODIFY total_score DECIMAL(5,2) NULL;
SET @campus_old_check = (SELECT tc.constraint_name FROM information_schema.table_constraints tc JOIN information_schema.check_constraints cc ON cc.constraint_schema=tc.constraint_schema AND cc.constraint_name=tc.constraint_name WHERE tc.table_schema=DATABASE() AND tc.table_name='repair_order' AND tc.constraint_type='CHECK' AND cc.check_clause LIKE '%`status`%' AND tc.constraint_name<>'chk_repair_status_extended' LIMIT 1);
SET @campus_ddl = IF(@campus_old_check IS NULL, 'SELECT 1', CONCAT('ALTER TABLE repair_order DROP CHECK `',REPLACE(@campus_old_check,'`','``'),'`'));
PREPARE campus_stmt FROM @campus_ddl; EXECUTE campus_stmt; DEALLOCATE PREPARE campus_stmt;
SET @campus_ddl = IF((SELECT COUNT(*) FROM information_schema.table_constraints WHERE table_schema=DATABASE() AND table_name='repair_order' AND constraint_name='chk_repair_status_extended')=0, "ALTER TABLE repair_order ADD CONSTRAINT chk_repair_status_extended CHECK(status IN('CREATED','WAIT_AUDIT','WAIT_ASSIGN','ASSIGNED','PROCESSING','WAIT_CONFIRM','FINISHED','COMMENTED','REJECTED','REWORK_PENDING'))", 'SELECT 1');
PREPARE campus_stmt FROM @campus_ddl; EXECUTE campus_stmt; DEALLOCATE PREPARE campus_stmt;
SET @campus_ddl = IF(@campus_new_workflow, 'UPDATE repair_order o SET update_time=o.update_time, assigned_time=(SELECT MAX(e.create_time) FROM order_event e WHERE e.order_id=o.id AND e.action=\'ASSIGN\'), accepted_time=CASE WHEN o.status IN(\'ASSIGNED\',\'PROCESSING\',\'WAIT_CONFIRM\',\'FINISHED\',\'COMMENTED\') THEN COALESCE((SELECT MAX(e.create_time) FROM order_event e WHERE e.order_id=o.id AND e.action=\'ACCEPT\'),(SELECT MAX(e.create_time) FROM order_event e WHERE e.order_id=o.id AND e.action=\'ASSIGN\'),o.update_time) ELSE NULL END, started_time=(SELECT MAX(e.create_time) FROM order_event e WHERE e.order_id=o.id AND e.action=\'START\'), dispatch_round=CASE WHEN o.worker_id IS NULL THEN 0 ELSE 1 END', 'SELECT 1');
PREPARE campus_stmt FROM @campus_ddl; EXECUTE campus_stmt; DEALLOCATE PREPARE campus_stmt;
UPDATE dispatch_record SET decision='ASSIGNED' WHERE confirmed=1 AND decision='RECOMMENDED';
SET @campus_ddl = IF(@campus_new_workflow, 'UPDATE dispatch_record SET round_no=1 WHERE round_no=0', 'SELECT 1');
PREPARE campus_stmt FROM @campus_ddl; EXECUTE campus_stmt; DEALLOCATE PREPARE campus_stmt;
SET @campus_ddl = IF(@campus_new_workflow, 'INSERT INTO dispatch_record(order_id,worker_id,reason,recommendation_batch,confirmed,create_time,round_no,decision,method) SELECT o.id,o.worker_id,\'历史人工指定，未使用评分模型\',UUID(),1,e.create_time,1,IF(o.accepted_time IS NULL,\'ASSIGNED\',\'ACCEPTED\'),\'MANUAL\' FROM repair_order o JOIN order_event e ON e.order_id=o.id AND e.action=\'ASSIGN\' WHERE o.worker_id IS NOT NULL AND e.id=(SELECT MAX(last_event.id) FROM order_event last_event WHERE last_event.order_id=o.id AND last_event.action=\'ASSIGN\') AND NOT EXISTS(SELECT 1 FROM dispatch_record d WHERE d.order_id=o.id AND d.confirmed=1)', 'SELECT 1');
PREPARE campus_stmt FROM @campus_ddl; EXECUTE campus_stmt; DEALLOCATE PREPARE campus_stmt;

-- Legacy orders keep their current acceptance semantics. SLA defaults apply to the first upgrade only.
SET @campus_ddl = IF(@campus_new_workflow, 'UPDATE repair_order SET update_time=update_time,response_due_time=DATE_ADD(assigned_time,INTERVAL CASE priority WHEN \'HIGH\' THEN 2 WHEN \'LOW\' THEN 24 ELSE 8 END HOUR) WHERE worker_id IS NOT NULL AND accepted_time IS NULL AND status IN(\'WAIT_ASSIGN\',\'ASSIGNED\') AND assigned_time IS NOT NULL', 'SELECT 1');
PREPARE campus_stmt FROM @campus_ddl; EXECUTE campus_stmt; DEALLOCATE PREPARE campus_stmt;
SET @campus_ddl = IF(@campus_new_workflow, 'UPDATE repair_order SET update_time=update_time,repair_due_time=DATE_ADD(started_time,INTERVAL CASE priority WHEN \'HIGH\' THEN 8 WHEN \'LOW\' THEN 72 ELSE 24 END HOUR) WHERE status=\'PROCESSING\' AND started_time IS NOT NULL', 'SELECT 1');
PREPARE campus_stmt FROM @campus_ddl; EXECUTE campus_stmt; DEALLOCATE PREPARE campus_stmt;
SET @campus_ddl = IF((SELECT COUNT(*) FROM information_schema.statistics WHERE table_schema=DATABASE() AND table_name='repair_order' AND index_name='idx_order_response_sla')=0, 'CREATE INDEX idx_order_response_sla ON repair_order(overdue_type,status,response_due_time,id)', 'SELECT 1');
PREPARE campus_stmt FROM @campus_ddl; EXECUTE campus_stmt; DEALLOCATE PREPARE campus_stmt;
SET @campus_ddl = IF((SELECT COUNT(*) FROM information_schema.statistics WHERE table_schema=DATABASE() AND table_name='repair_order' AND index_name='idx_order_repair_sla')=0, 'CREATE INDEX idx_order_repair_sla ON repair_order(overdue_type,status,repair_due_time,id)', 'SELECT 1');
PREPARE campus_stmt FROM @campus_ddl; EXECUTE campus_stmt; DEALLOCATE PREPARE campus_stmt;
SET @campus_ddl = IF((SELECT COUNT(*) FROM information_schema.statistics WHERE table_schema=DATABASE() AND table_name='dispatch_record' AND index_name='idx_dispatch_round')=0, 'CREATE INDEX idx_dispatch_round ON dispatch_record(order_id,round_no,confirmed)', 'SELECT 1');
PREPARE campus_stmt FROM @campus_ddl; EXECUTE campus_stmt; DEALLOCATE PREPARE campus_stmt;
SET @campus_ddl = IF((SELECT COUNT(*) FROM information_schema.statistics WHERE table_schema=DATABASE() AND table_name='repair_record' AND index_name='idx_repair_round')=0, 'CREATE INDEX idx_repair_round ON repair_record(order_id,round_no)', 'SELECT 1');
PREPARE campus_stmt FROM @campus_ddl; EXECUTE campus_stmt; DEALLOCATE PREPARE campus_stmt;

-- A final marker survives partial DDL failure; rerunning finishes legacy backfills before marking complete.
SET @campus_ddl = IF(@campus_new_workflow, 'UPDATE dispatch_record d JOIN repair_order o ON o.id=d.order_id SET d.decision=\'ACCEPTED\',d.response_time=o.accepted_time WHERE d.confirmed=1 AND o.accepted_time IS NOT NULL', 'SELECT 1');
PREPARE campus_stmt FROM @campus_ddl; EXECUTE campus_stmt; DEALLOCATE PREPARE campus_stmt;
SET @campus_ddl = IF(@campus_new_workflow, 'ALTER TABLE repair_order ADD CONSTRAINT chk_workflow_migration_complete CHECK(repair_round>=1)', 'SELECT 1');
PREPARE campus_stmt FROM @campus_ddl; EXECUTE campus_stmt; DEALLOCATE PREPARE campus_stmt;
