-- Phase 3 增量结构，不删除或修改 Phase 1/2 用户数据。重复执行安全。
USE campus_repair;
SET NAMES utf8mb4;
CREATE TABLE IF NOT EXISTS building (
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
 name VARCHAR(80) NOT NULL UNIQUE, type VARCHAR(30) NOT NULL,
 longitude DECIMAL(10,7) NULL, latitude DECIMAL(10,7) NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE IF NOT EXISTS repair_type (
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
 name VARCHAR(60) NOT NULL UNIQUE, description VARCHAR(300) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE IF NOT EXISTS student (
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
 user_id BIGINT UNSIGNED NOT NULL UNIQUE, student_no VARCHAR(40) NOT NULL UNIQUE,
 college VARCHAR(80) NOT NULL, class_name VARCHAR(80) NOT NULL,
 building_id BIGINT UNSIGNED NULL, room_no VARCHAR(30) NULL,
 FOREIGN KEY(user_id) REFERENCES `user`(id), FOREIGN KEY(building_id) REFERENCES building(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE IF NOT EXISTS worker (
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
 user_id BIGINT UNSIGNED NOT NULL UNIQUE, skill_type VARCHAR(80) NOT NULL,
 score DECIMAL(3,2) NOT NULL DEFAULT 0, task_count INT NOT NULL DEFAULT 0, status TINYINT NOT NULL DEFAULT 1,
 FOREIGN KEY(user_id) REFERENCES `user`(id), CHECK(score BETWEEN 0 AND 5), CHECK(task_count>=0), CHECK(status IN(0,1))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE IF NOT EXISTS repair_order (
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
 student_id BIGINT UNSIGNED NOT NULL, type_id BIGINT UNSIGNED NOT NULL,
 title VARCHAR(120) NOT NULL, description VARCHAR(2000) NOT NULL, image_url VARCHAR(100) NULL,
 building_id BIGINT UNSIGNED NOT NULL, room_no VARCHAR(30) NOT NULL,
 priority VARCHAR(16) NOT NULL DEFAULT 'NORMAL', status VARCHAR(24) NOT NULL,
 worker_id BIGINT UNSIGNED NULL,
 create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
 update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
 FOREIGN KEY(student_id) REFERENCES student(id), FOREIGN KEY(type_id) REFERENCES repair_type(id),
 FOREIGN KEY(building_id) REFERENCES building(id), FOREIGN KEY(worker_id) REFERENCES worker(id),
 INDEX idx_student_time(student_id,create_time,id), INDEX idx_worker_status(worker_id,status,id),
 INDEX idx_status_time(status,create_time,id), INDEX idx_type_time(type_id,create_time),
 CHECK(priority IN('LOW','NORMAL','HIGH')),
 CHECK(status IN('CREATED','WAIT_AUDIT','WAIT_ASSIGN','ASSIGNED','PROCESSING','WAIT_CONFIRM','FINISHED','COMMENTED'))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE IF NOT EXISTS repair_record (
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
 order_id BIGINT UNSIGNED NOT NULL, worker_id BIGINT UNSIGNED NOT NULL,
 content VARCHAR(2000) NOT NULL, image_url VARCHAR(100) NULL,
 start_time DATETIME NOT NULL, finish_time DATETIME NULL,
 FOREIGN KEY(order_id) REFERENCES repair_order(id), FOREIGN KEY(worker_id) REFERENCES worker(id), INDEX idx_record_order(order_id,id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE IF NOT EXISTS evaluation (
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
 order_id BIGINT UNSIGNED NOT NULL UNIQUE, student_id BIGINT UNSIGNED NOT NULL,
 score TINYINT NOT NULL, content VARCHAR(1000) NOT NULL DEFAULT '',
 create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
 FOREIGN KEY(order_id) REFERENCES repair_order(id), FOREIGN KEY(student_id) REFERENCES student(id), CHECK(score BETWEEN 1 AND 5)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE IF NOT EXISTS order_event (
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, order_id BIGINT UNSIGNED NOT NULL,
 actor_id BIGINT UNSIGNED NOT NULL, action VARCHAR(20) NOT NULL, status VARCHAR(24) NOT NULL,
 create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
 FOREIGN KEY(order_id) REFERENCES repair_order(id), FOREIGN KEY(actor_id) REFERENCES `user`(id), INDEX idx_event_order(order_id,id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE IF NOT EXISTS repair_image (
 id VARCHAR(36) CHARACTER SET ascii COLLATE ascii_bin PRIMARY KEY,
 owner_id BIGINT UNSIGNED NOT NULL, order_id BIGINT UNSIGNED NULL, content_type VARCHAR(40) NOT NULL,
 create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
 FOREIGN KEY(owner_id) REFERENCES `user`(id), FOREIGN KEY(order_id) REFERENCES repair_order(id), INDEX idx_image_order(order_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
INSERT INTO building(name,type) VALUES('学生宿舍1号楼','DORMITORY'),('教学楼A栋','TEACHING'),('校园图书馆','LIBRARY')
 ON DUPLICATE KEY UPDATE name=name;
INSERT INTO repair_type(name,description) VALUES('照明与电路','灯具、开关、插座及电路故障'),('给排水','水龙头、管道、排水及漏水问题'),('门窗与家具','门锁、窗户、桌椅及家具损坏'),('空调与设备','空调、风扇及其他公共设备故障'),('其他问题','其他需要校园后勤协助处理的问题')
 ON DUPLICATE KEY UPDATE name=name;
